### ISSUE TITLE
Error creating a DAO:  Cannot create instance of Avatar; no code at address

### ISSUE THREAD

**Issue by dkent600** [daostack/arc-js#15]
Intermittently, when trying to create a DAO on kovan, I am getting a failure with the following message:

> Unhandled rejection Error: Cannot create instance of Avatar; no code at address 0x[...]

I am using a local kovan node (Parity) with a locked account, so I'm not having to sign anything, which means steps are proceeding a bit faster than usual.  The problem doesn't happen using testrpc, seem to happen less often (or not at all?) using metamask.

The result is a corrupt DAO.

I believe the problem must be occurring as follows:

In `Organization.new`, `Avatar.at` is not finding code at the address given in the log:

```
const tx = await genesisScheme.forgeOrg(
      options.orgName,
      options.tokenName,
      options.tokenSymbol,
      options.founders.map(x => x.address),
      options.founders.map(x => x.tokens),
      options.founders.map(x => x.reputation),
    );
    // get the address of the avatar from the logs
    const avatarAddress = getValueFromLogs(tx, '_avatar');
    const org = new Organization();

    options.avatar = avatarAddress;
    org.avatar = await Avatar.at(options.avatar);
```

There _is_ code however.  Here is one example of an Avatar that could not be found:  https://kovan.etherscan.io/address/0x03bfdd4c2e6a490d2acd4cbd66b4d1d24af8a97c

My guess:  We're getting a log of a "pending" transaction....

**Comment by dkent600** [comment]
@tibetsprague @leviadam tagging you for your interest, and in case you have any easy insights....

**Comment by dkent600** [comment]
Related issues:
https://github.com/daostack/Alchemy-Aurelia/issues/1
https://github.com/daostack/arc-js/issues/9

**Comment by leviadam** [comment]
Is this fixed @dkent600 ?

**Comment by dkent600** [comment]
I think this probably happens when my Parity node is not "caught up".  Closing unless/until this is proven otherwise.
